name:                hc-katip
version:             0.1.0.0
license:             BSD3

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- unordered-containers
- katip
- scientific
- text
- vector

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  m:
    source-dirs:         app
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hc-katip

tests:
  spec:
    source-dirs:         test
    main:                Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hc-katip
    - hspec
    - hspec-expectations

