name:                myrio
version:             0.1.0.0

dependencies:
- base >= 4.10 && < 10
- rio >= 0.1.1.0

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  main:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - myrio
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
