name:                artyom-lens-over-tea
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- cereal
- containers
- lens

library:
  source-dirs: src

tests:
  artyom-lens-over-tea-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - artyom-lens-over-tea
