resolver: lts-12.10
packages:
- .
- location:
    git: git@github.com:haroldcarr/test-hunit-util.git
    commit: 17971cdff83473fe044c7ea82aade2ed6afc47ed
  extra-dep: true
# extra-deps: []
# flags: {}
# extra-package-dbs: []
