name:                hc-dhall
version:             0.1.0.0

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5
- dhall
- text

library:
  source-dirs: src

executables:
  m:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hc-dhall

tests:
  test:
    main:                hspec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hc-dhall
    - hspec
    - hspec-expectations
