name:                bank-account
version:             0.1.0.0
github:              "githubuser/bank-account"
license:             BSD3
author:              "Harold Carr"

description:         Please see the README on GitHub at <https://github.com/githubuser/bank-account#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- mtl
- protolude
- text
- time
- transformers

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  main:
    source-dirs:         app
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bank-account

tests:
  test:
    source-dirs:         test
    main:                XTestDriver.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bank-account
    - dejafu
    - hunit-dejafu
    - process
    - QuickCheck
    - quickcheck-state-machine
    - tasty
    - tasty-dejafu
    - tasty-discover
    - tasty-expected-failure
    - tasty-hunit
    - tasty-quickcheck
    - tree-diff
