name:                hc-has-field
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- cereal
- containers
- lens
- mtl

library:
  source-dirs: src

tests:
  hc-has-field-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hc-has-field
