name:                hc
version:             0.1.0.0

dependencies:
- base >= 4.10 && < 10
- pretty-show
- rio
- rio-orphans

# configuration
- aeson
- componentm
- componentm-devel
- etc
- file-embed

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  main:
    source-dirs:         app
    main:                Main.hs
    dependencies:
    - hc
    - optparse-simple
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  hc-test:
    source-dirs:         test
    main:                Spec.hs
    dependencies:
    - hc
    - hspec

    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
