name:                tapl
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- protolude

ghc-options:
- -Wall
- -fwarn-redundant-constraints

library:
  source-dirs: src

tests:
  t:
    source-dirs:         test
    main:                hspec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hspec-expectations
    - tapl
