name:                iceland-jack
version:             0.1.0.0

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5
- kan-extensions
- simple-reflect

library:
  source-dirs: src

executables:
  iceland-jack-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iceland-jack

tests:
  iceland-jack-test:
    source-dirs:         test
    main:                hspec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hspec-expectations
    - iceland-jack

