name:                csongor-kiss-higher-order-type-level
version:             0.1.0.0
github:              "githubuser/csongor-kiss-higher-order-type-level"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

dependencies:
- base >= 4.7 && < 5
- text

ghc-options:
- -Wall
- -fwarn-redundant-constraints

library:
  source-dirs: .
