name:                bank-account
version:             0.1.0.0
github:              "githubuser/bank-account"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bank-account#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- mtl
- protolude
- time
- transformers

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  main:
    source-dirs:         app
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bank-account

tests:
  test:
    source-dirs:         test
    main:                XTestDriver.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bank-account
    - dejafu
    - hunit-dejafu
    - process
    - QuickCheck
    - quickcheck-state-machine
    - tasty
    - tasty-dejafu
    - tasty-discover
    - tasty-expected-failure
    - tasty-hunit
    - tasty-quickcheck
    - tree-diff
