name:                mark-karpov-ghc-generics-explained
version:             0.1.0.0

ghc-options:
- -Wall
- -fwarn-redundant-constraints

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  main:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mark-karpov-ghc-generics-explained

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mark-karpov-ghc-generics-explained
    - hspec
