name:                hcrio
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- rio

library:
  source-dirs: src

executables:
  main:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hcrio

tests:
  hcrio-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hcrio
