name:                applied-haskell-snoyman
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- conduit
- deepseq
- mtl
- vector

library:
  source-dirs:
  - src
  ghc-options:
  - -Wall

executables:
  average:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - applied-haskell-snoyman
