name:                chris-done-data-typeable
version:             0.1.0.0

ghc-options:
- -Wall
- -fwarn-redundant-constraints

dependencies:
- base >= 4.7 && < 5
- hspec
- syb
- transformers

library:
  source-dirs: src

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chris-done-data-typeable
