name:                juno
version:             0.1.0.0
license:             BSD3

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- lens
- mtl
- random
- thyme

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  m:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - juno
