name:                structure-log-lines
version:             0.1.0.0
license:             BSD3

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- juno
- text
- unordered-containers
- vector

ghc-options:
- -Wall

library:
  source-dirs: src

tests:
  spec:
    source-dirs:         test
    main:                Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - structure-log-lines
    - hspec
    - hspec-expectations

