name:                matt-noonan-ghosts-of-departed-proofs
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- containers
- extra
- MissingH

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  matt-noonan-ghosts-of-departed-proofs-exe:
    source-dirs:         app
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - matt-noonan-ghosts-of-departed-proofs

tests:
  matt-noonan-ghosts-of-departed-proofs-test:
    source-dirs:         test
    main:                Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - matt-noonan-ghosts-of-departed-proofs
