name:                misc
version:             0.1.0.0

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  misc-test:
    source-dirs:         test
    main:                Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - misc
